### ISSUE TITLE
when I run pimd on ubuntu it throws an error "Another multicast routing application is already running."

### ISSUE THREAD

**Issue by shockingchen** [troglobit/pimd#195] opened 2021-08-02 07:09 UTC
root@ubuntu:/etc# pimd
pimd: 15:07:53.765 Ignoring ens38, same subnet as ens33
pimd: 15:07:53.765 Another multicast routing application is already running.
root@ubuntu:/etc# cat /proc/version
Linux version 4.15.0-29-generic (buildd@lgw01-amd64-057) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018

whar is the root cause? thank you.

**Comment by troglobit** [comment] 2021-08-02 07:21
1. What version of pimd are you using?
 2. The multicast routing stack only allows one routing daemon at a time (except if you use policy routing/tables)
 3. The root cause is that you probably have another multicast routing daemon running, e.g. smcrouted, mrouted, or more likely another pimd instance in the background

**Comment by shockingchen** [comment] 2021-08-02 07:35
hi，it seems I did not install the mrouted,smcrouted,how can I find the Another multicast routing application? which port is listening by the pimd?

pimd version 2.3.2

root@ubuntu:/etc# pimd -v
pimd version 2.3.2
root@ubuntu:/etc# pimd -d
debug level 0xffffffff (dvmrp_detail,dvmrp_prunes,dvmrp_routes,dvmrp_neighbors,dvmrp_timers,igmp_proto,igmp_timers,igmp_members,trace,timeout,packets,interfaces,kernel,cache,rsrr,pim_detail,pim_hello,pim_register,pim_join_prune,pim_bootstrap,pim_asserts,pim_cand_rp,pim_routes,pim_timers,pim_rpf)
15:32:28.626 pimd version 2.3.2 starting ...
15:32:28.626 Got 262144 byte send buffer size in 0 iterations
15:32:28.626 Got 262144 byte recv buffer size in 0 iterations
15:32:28.626 Got 262144 byte send buffer size in 0 iterations
15:32:28.626 Got 262144 byte recv buffer size in 0 iterations
15:32:28.626 Getting vifs from kernel
15:32:28.626 Installing ens33 (192.168.138.131 on subnet 192.168.138) as vif #0-2 - rate 0
15:32:28.626 Ignoring ens38, same subnet as ens33
15:32:28.626 Getting vifs from /etc/pimd.conf
15:32:28.626 Local Cand-BSR address 192.168.138.131, priority 5
15:32:28.626 Local Cand-RP address 192.168.138.131, priority 20, interval 30 sec
15:32:28.626 spt-threshold packets 0 interval 100
15:32:28.626 Local static RP: 169.254.0.1, group 232.0.0.0/8
15:32:28.626 IGMP query interval  : 12 sec
15:32:28.626 IGMP querier timeout : 41 sec
15:32:28.626 Another multicast routing application is already running.
root@ubuntu:/etc# smcrouted

Command 'smcrouted' not found, did you mean:

  command 'smcroute' from deb smcroute

Try: apt install <deb name>

root@ubuntu:/etc# mrouted
mrouted: command not found

**Comment by troglobit** [comment] 2021-08-02 10:35
If you've installed pimd as a .deb packlage from Ubuntu then it's likely already running in the background. Check your ps output, e.g.

    ps fax |grep pimd

**Comment by shockingchen** [comment] 2021-08-03 02:31
thank you,it seems can be started. I did not do anything change,just reboot the linux today?

**Comment by troglobit** [comment] 2021-08-03 06:45
OK, not a bug then, so closing this issue report.

**Closed by troglobit** 2021-08-03 06:45 UTC
