### ISSUE TITLE
Problem with pimd when more 300 secondary IPs used in vif 

### ISSUE THREAD

**Issue by rdpmc** [troglobit/pimd#221] opened 2022-03-16 17:54 UTC
Hello, when I use pimd setup in a router,where one if vifs in pim is the ethernet iface,and this interface has more then 300 adresses(i checked 600), then multicast traffic stops to forward.
All works when used 300 IPs, when 600 - this problem exists. I don't know the exact limit.

My scheme : sender----r1----RP---r3----recv.

Net1 between sender and r1 , net2 between r1 abd rp(randevu), net3 - between rp and r3, net4 - between r3 and recv.
Rp is static.

Problem is in r3 : it has 2 ifaces in pim and one of ifaces has many ip adresses (all from one net with netmask /16)

Why this happens and how to overcome this?
I need about 1000 ip adresses in one interface ,that is used in pim.

Thanks.

**Comment by troglobit** [comment] 2022-03-16 22:04
Thank you for the report.  Although this may not be out of spec, it's definitely out of scope of this project at the moment. I suggest you find a corporate sponsor to help you out debugging this issue and send a PR to this project when you've root caused the problem.  There is is exactly nobody right now that would help you fix this problem free of charge.

**Closed** 2022-03-17 17:49 UTC

**Comment by rdpmc** [comment] 2022-03-17 17:50
You may close issue. It was my fault: 1 of IP addresses was the same as on another router.
