### ISSUE TITLE
Crash in (S,G) state when neighbor is lost

### ISSUE THREAD

**Issue by YileKu** [troglobit/pimd#22] opened 2013-10-02 15:07 UTC
I had to add the following code to the bottom of delete_pim_nbr():

     for (cand_rp_ptr = cand_rp_list; cand_rp_ptr != (cand_rp_t *)NULL;
         cand_rp_ptr = cand_rp_ptr->next) {
        for (rp_grp_entry_ptr = cand_rp_ptr->rp_grp_next;
            rp_grp_entry_ptr != (rp_grp_entry_t *)NULL;
            rp_grp_entry_ptr = rp_grp_entry_ptr->rp_grp_next)
            {
           for (grpentry_ptr = rp_grp_entry_ptr->grplink;
               grpentry_ptr != (grpentry_t *)NULL;
               grpentry_ptr = grpentry_ptr->next) {
                mrtentry_srcs = grpentry_ptr->grp_route;
                if (mrtentry_srcs != NULL ) {
                  if(mrtentry_srcs->upstream != NULL) {
                      if (mrtentry_srcs->upstream == nbr_delete) {
                         mrtentry_srcs->upstream = NULL;
                      }
                  }
             }
        }
    }
    }

age_routes was crashing because upstream had been freed, then someone else (timer_setTimer) was allocating the freed memory and clobbering the bjpm pointer.
Y-

**Comment by idismmxiv** [comment] 2015-03-14 16:57
Looks like version 2.2.0 works just fine. Could not reproduce this error any more.

**Comment by troglobit** [comment] 2015-03-14 17:07
@idismmxiv That is truly great news, then we can close this, thank you! :-)

**Comment by mfspeer** [comment] 2015-03-18 15:52
See issue #37

**Comment by troglobit** [comment] 2015-03-21 14:42
Reopen due to #37.

**Comment by mfspeer** [comment] 2015-03-23 18:02
In stop_vif(), I patched this:
   if (!(v->uv_flags & VIFF_REGISTER)) {
        RESET_TIMER(v->uv_pim_hello_timer);
        RESET_TIMER(v->uv_jp_timer);
        RESET_TIMER(v->uv_gq_timer);

        for (n = v->uv_pim_neighbors; n != NULL; n = next) {
            next = n->next;     /* Free the space for each neighbour */
#if defined(PLURIBUS_BUG_FIX)
            delete_pim_nbr(n);
#else
            free(n);
#endif
        }
        v->uv_pim_neighbors = NULL;
    }

and in delete_pim_nbr, I added this as well:
    if (!v->uv_pim_neighbors) {
        /* This was our last neighbor. */
        v->uv_flags &= ~VIFF_PIM_NBR;
        v->uv_flags |= (VIFF_NONBRS | VIFF_DR);
#if defined(PLURIBUS_BUG_FIX)
        RESET_TIMER(v->uv_jp_timer);
#endif
    } else {
        if (ntohl(v->uv_lcl_addr) > ntohl(v->uv_pim_neighbors->address))
            /* The first address is the new potential remote
             * DR address, but the local address is the winner.
             */
            v->uv_flags |= VIFF_DR;
    }

This for the moment seems to have calmed the storm.

**Comment by mfspeer** [comment] 2015-03-23 18:06
I take it back, the change to delete_pim_nbr() is not required.

**Comment by mfspeer** [comment] 2015-04-01 20:38
Any update on suggested fix?

**Comment by troglobit** [comment] 2015-04-13 04:39
Interesting, so all you changed was to replace `free(n)` with `delete_pim_nbr(n)`?
I could probably go with that.

**Comment by troglobit** [comment] 2015-04-20 04:58
I sincerely hope 69a5e34 fixes this bug, once and for all!

I'm now closing this issue as fixed in v2.2.1, but if it creeps up again, please reopen. Cheers, and thanks for all the help debugging and coming up with this fix, @mfspeer :)

**Closed** 2015-04-20 04:58 UTC
