### ISSUE TITLE
Replacement of igmpproxy with pimd

### ISSUE THREAD

**Issue by mirtouf** [troglobit/pimd#141] opened 2019-02-24 19:12 UTC
Hi,

I am running a pfsense box and in first approach I thought igmpproxy was the first solution to access multicast streams as IGMP announces are sent by my ISP (I read the mutlicast howto).
Nevertheless, using igmpproxy works only if I start first pimd, kill it and then start again igmpproxy.

my pimd.conf
```
# These two are only needed if pimd is stared with -N flag
phyint igb0.100 enable igmpv2
phyint igb1 enable igmpv2
# Used for more complex topologies, but is OK to keep anyway
spt-threshold packets 0 interval 100
# These two are requried in case more PIM routers are available
bsr-candidate priority 5
rp-candidate time 30 priority 20
```
my igmpproxy.conf
```
##------------------------------------------------------
## Enable Quickleave mode (Sends Leave instantly)
##------------------------------------------------------
quickleave
phyint igb0.100 upstream ratelimit 0 threshold 1
altnet 193.251.97.0/24
altnet 89.86.97.0/24
altnet 176.165.8.0/24
altnet 89.86.96.0/24

phyint igb1 downstream ratelimit 0 threshold 1
altnet 192.168.1.0/24
```
I did captures using the router provided by my ISP with a bridge and I have only seen IGMPv2 packets, no PIM-SM packets. The router is using address 0.0.0.0 to send IGMP announces.

My question is to know which good thing is performing pimd which allows me to use igmpproxy after.

I agree this is not a real bug report but I did not find any ML for pimd.

cheers,

**Comment by troglobit** [comment] 2019-02-25 09:40
As you say, this is not a bug in pimd, so I'm closing this issue.

I suggest to ask the igmpproxy project why their program does not work.

**Closed by troglobit** 2019-02-25 09:40 UTC
